2018-07-19 12:37:41,265 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:00:43,716 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:01:05,189 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:27:19,767 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:27:50,149 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:28:34,174 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:44:05,020 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:45:42,070 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:47:15,055 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:49:58,542 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:50:53,168 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 13:52:57,326 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-19 17:09:04,080 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-20 12:36:07,244 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-20 13:10:54,207 ERROR: Exception on /orders/reload [GET] [in /usr/local/lib/python3.4/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/main/routes.py", line 115, in reload
    orders=OrderDfs(current_app.config['DBSTR'])
NameError: name 'OrderDfs' is not defined
2018-07-20 13:15:35,977 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 11:47:39,340 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 12:08:54,360 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 12:09:32,176 ERROR: Exception on /orders/reload [GET] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/main/routes.py", line 116, in reload
    orders=OrderDfs(current_app.config['DBSTR'])
TypeError: __init__() takes 1 positional argument but 2 were given
2018-07-21 12:12:03,254 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 12:22:32,320 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 12:27:04,995 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:43]
2018-07-21 13:17:04,662 INFO: Orders analysis app startup [in /home/victorl/Documents/DIPLOMADO-UPEL-EducacionUniversitaria/TEMAS-o-AREAS/COMPUTER-SCIENCE/EJEMPLOS/PYTHON/FLASK/plot-northwind/webapp/__init__.py:44]
2018-07-21 13:17:30,374 ERROR: Exception on /orders/reload [GET] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2018-07-21 13:18:21,851 ERROR: Exception on /orders/reload [GET] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
